spin_manifest_version = 2

[application]
name = "wordgame"
version = "0.1.0"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = "a game. with words."

[[trigger.http]]
route = "/..."
component = "wordgame"

[component.wordgame]
source = "target/wasm32-wasi/release/wordgame.wasm"
files = ["words.txt"]
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.wordgame.build]
command = "cargo leptos build --release && LEPTOS_OUTPUT_NAME=wordgame cargo build --lib --target wasm32-wasi --release --no-default-features --features ssr"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "pkg"

[component.pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "target/site/pkg", destination = "/" }]
